
export OMP_NUM_THREADS=8
echo SPCElanczoslogBacic70pt20potNoAcosIndex_8threads_fraction
time ./LanczosTOBYfraction LanczosInputFileToby5.txt HvInputFileToby70pt.txt > /scratch/jtcantin/SPCElanczoslogBacic70pt20potNoAcosIndex_8threads_fraction
